### ISSUE TITLE
Why disable floats?

### ISSUE THREAD

**Issue by SimonSapin** [intermezzOS/libcore#1]
From `README.md`:

> Thanks to @thepowersgang and @phil-opp for their ‘remove floats from libcore’ patches and projects.

[…]

> To build:
>     $ cargo build --release --features disable_float --target=x86_64-unknown-intermezzos-gnu

Why is it necessary to exclude code related to `f32` or `f64`?

http://os.phil-opp.com/set-up-rust.html mentions linker errors like:

```
target/debug/libblog_os.a(core-35017696.0.o): In function `ops::f32.Rem::rem::hfcbbcbe5711a6e6emxm':
core.0.rs:(.text._ZN3ops7f32.Rem3rem20hfcbbcbe5711a6e6emxmE+0x1): undefined reference to `fmodf'
target/debug/libblog_os.a(core-35017696.0.o): In function `ops::f64.Rem::rem::hbf225030671c7a35Txm':
core.0.rs:(.text._ZN3ops7f64.Rem3rem20hbf225030671c7a35TxmE+0x1): undefined reference to `fmod'
```

… which looks very similar to the previous linker error in that post: `undefined reference to 'memcpy'`. The solution for that one was to include the `rlibc` crate. Should `fmod` and `fmodf` be added to `rlibc`? Porting the ones from musl (MIT licensed) to Rust seems doable:

http://git.musl-libc.org/cgit/musl/tree/src/math/fmod.c
http://git.musl-libc.org/cgit/musl/tree/src/math/fmodf.c

CC @alexcrichton for rlibc.

**Comment by thepowersgang** [comment]
In kernels, it's both about avoiding needing libm (which is the undefined reference issue) - But the main point is to avoid needing SSE enabled on x86-64. If SSE is enabled, llvm will use it to optimise memory copies. With it disabled, use of floating point values will lead to a compile-time error. The patched libcore is to avoid that compile-time error.

SSE (and other register set extensions) is undesirable because of the larger set of registers that need to be maintained on context switches (e.g. interrupts)

**Comment by steveklabnik** [comment]
This is all accurate, but also, this custom libcore isn't needed anymore, so closing regardless :smile:
